### ISSUE TITLE
Access Token getting deleted from localstorage

### ISSUE THREAD

**Issue by thunderysteak** [posttwo/fjmod-extension#14]
Access Token getting deleted from localstorage by either accidental user deletion, chrome itself or by other extensions
Workaround needed

**Comment by posttwo** [comment]
chrome.storage.sync is the fix but that means I cant copy paste it like a dummy to firefox when im tired of chrome :(

**Comment by posttwo** [comment]
also would require window messaging and/or moving everything from injected scripts to content scripts

**Comment by posttwo** [comment]
wish I could add features straight to funnyjunk

**Comment by thunderysteak** [comment]
Ask admin if it's possible to add a mod identifier (Hidden element in code) that could replace the token system and automatically detect that the extension user is a mod

**Comment by posttwo** [comment]
He would need to give an api endpoint for fjmod to verify the username and mod status
Was thinking of making a bot that works via PMs @_@

**Comment by thunderysteak** [comment]
How about creating a bot that will verify an user as a mod and generate new token when requested? Something like old Garrysmod.org verification method before Steam's OAuth was a thing
- Bot instructs mod to enable their mod rewards and make their profile public
- Bot gives mod a random string to place into their profile description
- Bot verifies that the user is a mod by checking if a mod reward icon is found on the profile
- Bot also verifies the mod's identity by finding the random string on the page
- After verification is finished, bot spits out a randomly generated Authentication Token for user 

This eliminates the need to fix this bug

**Comment by posttwo** [comment]
Replace "bot" by "Felris" and you have the current setup :^ )

**Comment by posttwo** [comment]
FunnyJunk OAuth would be nice imo

**Comment by posttwo** [comment]
Can fix if I would change https://github.com/posttwo/fjmod-extension/blob/bb9c262330f8afd1075f002175f2b4f35b603665/src/inject/inject.js#L56 to chrome.storage.sync or whatever.

**Comment by posttwo** [comment]
Anyway
fjmodbot should be enough to take care of this for now
