### ISSUE TITLE
Rich notification when new content in /sfw_mod/

### ISSUE THREAD

**Issue by thunderysteak** [posttwo/fjmod-extension#16]
How about displaying a rich notification when user is tabbed out of sfw_mod that also displays a text snippet of a new content (Content title and description or comment text.) using the chrome.notifications API

In order to not overload the mod's browser with ton of notifications and prevent leading to system halt/browser crash on toasters, #15 should get fixed first before doing this

**Comment by posttwo** [comment]
Ye but at the same time the whole existence of the feature which enables #8  is literally a hack https://github.com/posttwo/fjmod-extension/commit/25384847eee4cd708f68ccccf7b0bfaf88d3187f

Maybe once a better way to do it is found this could be revisited
