### ISSUE TITLE
Place "Clear cookies" to different place/add confirmation

### ISSUE THREAD

**Issue by thunderysteak** [posttwo/fjmod-extension#18]
The clear cookies button is in a dangerous place where a moderator can accidentally press it when trying to access the moderator settings, and it clears the FJ cookies without a confirmation, thus also purging the hide all list since that's saved locally 

Either place the clear cookies button into the moderator settings window or add a confirmation window

**Comment by posttwo** [comment]
> I fat fingered the clear cookies button
-@thunderysteak

**Comment by thunderysteak** [comment]
![admin can you change the anon name to quot that snitch quot _5026b0d47cd6a434b5b188afe122edff](https://cloud.githubusercontent.com/assets/16468437/20496948/92343648-b027-11e6-8a3c-d7d6d3734b11.png)

**Comment by thunderysteak** [comment]
Just marking down how the code should look what you posted yesterday
`$("span[title='Clear Cookies']").prop('onclick',null).off('click');
....onClick(function(){ .. })`
