### ISSUE TITLE
Add "Request Access Token" to moderator settings

### ISSUE THREAD

**Issue by thunderysteak** [posttwo/fjmod-extension#19]
Since there's now a FJ bot that can give mods their access token in case of accidental browser storage wipe or changed/new device, it would be good to place a button or a link to the page to request a new token

**Comment by posttwo** [comment]
First gotta make it be able to give it to new mods too

**Comment by thunderysteak** [comment]
"Request forgotten Access Token"

**Comment by posttwo** [comment]
That would also require me to make sure everyone has their proper username filled in
not like doggopupper :^ )

**Comment by posttwo** [comment]
Everyone now has a proper username

**Comment by thunderysteak** [comment]
What's the link to the bot request form again? I'll make a pull request with a button added to mod settings

**Comment by posttwo** [comment]
https://fjmod.posttwo.pt/token
I'll fix the random server error soonish, its already fixed in posttwo/funnyjunk just didnt update fjmod with it
put some message like "if server error, refresh lol"
