### ISSUE TITLE
Clean up the UI clutter in "Edit moderator settings"

### ISSUE THREAD

**Issue by thunderysteak** [posttwo/fjmod-extension#21]
Buttons not aligned, "Access Token" crammed to the buttons,...
Would be better if they were checkboxes to fit the FJ's design

![graphic_design_is_my_passion](https://cloud.githubusercontent.com/assets/16468437/20497136/4eef4a34-b028-11e6-8aa9-34c3e91994fd.jpg)

**Comment by posttwo** [comment]
https://github.com/posttwo/fjmod-extension/blob/90caee10ee5d1d80d99041a683427a6ef606c72d/src/js/main.js#L49

they're all buttons because I was too lazy to make a proper settings menu
could apply some styling and make them into categories I guess

**Comment by thunderysteak** [comment]
I'll try to do a pull request when I get time this week 
If not, keep the issue open

**Comment by thunderysteak** [comment]
Submitted pull request #22
