### ISSUE TITLE
Add changelog to the settings

### ISSUE THREAD

**Issue by thunderysteak** [posttwo/fjmod-extension#25]
Basically what the title says
It can't be done with iframe cuz of the cross-origin resource sharing policy Chrome has, so it needs to be updated manually and can't just show the Github's commit page

Also
jQuery tabs!

I'll try to figure out something when I'm hooked up on Vodka and feel like torturing myself 

btw add it to "A long time in the future, in the codebase far far away" milestone

**Comment by posttwo** [comment]
Would rather have an alert popup on update with a quick message what was changed

**Comment by thunderysteak** [comment]
How about doing both?
Doing 'alert("A new update for the mod extension is released! "+newChanges)' when a new version is released and when a cookie for that new version is missing

And then leaving a full changelog in the setting in a new tab with jQuery

**Comment by thunderysteak** [comment]
FJ's jQuery doesn't have the tab functions so any "tabs" are gonna just be JS DOM changes
And one specific trash panda wants to break my arms if I use iframes, so let's not do that

**Comment by thunderysteak** [comment]
Also nobody will ever bother checking the changelog, so the primary focus should be more at getting the UI of the mod panel streamlined because it's too bloated with too many buttons

NEW ISSUE TIEM
