### ISSUE TITLE
"Move ratings to bottom" broken after latest update by admin

### ISSUE THREAD

**Issue by thunderysteak** [posttwo/fjmod-extension#64]
![taskmgr_2017-09-02_14-58-00](https://user-images.githubusercontent.com/16468437/29995670-337e082e-8fef-11e7-8f22-ddac92e6fc19.png)
![taskmgr_2017-09-02_14-57-08](https://user-images.githubusercontent.com/16468437/29995671-3386ecb4-8fef-11e7-878c-8b1d052cc11d.png)

**Comment by Hunman** [comment]
There's two ways to fix this

1. Remove the event listener(s)
1. Overwrite the CSS that makes them float

And I'm tempted to go for the 2nd

**Comment by Hunman** [comment]
Fixed with CSS
